# -*- coding: utf-8 -*-
"""LaughterDetection_Interspeech.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lljiiHJXBPJWG4fmUJQuUAQ2s8EhBLGC

# Laughter Detection

* From https://github.com/omine-me/LaughterSegmentation/tree/main
* Works better than source separation + Voice Activity Detection
* Need to work with python 3.10
"""

!sudo apt-get update -y
!sudo apt-get install python3.10 python3.10-distutils -y

!wget https://bootstrap.pypa.io/get-pip.py
!python3.10 get-pip.py

!python3.10 --version

# Commented out IPython magic to ensure Python compatibility.
! git clone https://github.com/omine-me/LaughterSegmentation.git
# %cd LaughterSegmentation
! wget https://huggingface.co/omine-me/LaughterSegmentation/resolve/main/model.safetensors
! mv model.safetensors models/

!python3.10 -m pip install -r requirements.txt

"""Need to deal with this bug in order to read the wav file"""

!python3.10 -m pip uninstall -y pysoundfile
!python3.10 -m pip uninstall -y soundfile
!python3.10 -m pip install soundfile

! python3.10 inference.py --audio_path ../sample30.wav

! file ../output-audio.wav
! file ../sample30.wav

! python3.10 inference.py --audio_path ../output-audio.wav